name: eiv-grid-id
channels:
  - invenia
  - defaults
  - conda-forge
  - gurobi
dependencies:
  - ipywidgets=7.5.1
  - jupyterlab=2.2.8
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.1.2
  - plotly=4.10.0
  - seaborn=0.10.1
  - python=3.7.7
  - scipy=1.4.1
  - pytest=5.4.2
  - cvxpy=1.1.5
  - statsmodels=0.11.1
  - gurobi=9.0.2
  - tqdm=4.47.0
  - pip
  - pip:
      - pandapower==2.4.0
      - nbstripout==0.3.9
      - mlflow==1.11
