name: eiv-grid-id
channels:
  - invenia
  - defaults
  - conda-forge
  - gurobi
dependencies:
  - ipywidgets=7.5.1
  - jupyterlab=3.0.0
  - matplotlib=3.3.2
  - numpy=1.19.1
  - pandas=1.2.0
  - plotly=4.14.1
  - seaborn=0.11.1
  - python=3.7.7
  - xeus-python=0.9.4
  - scipy=1.5.2
  - pytest=6.2.1
  - cvxpy=1.1.7
  - statsmodels=0.11.1
  - gurobi=9.0.2
  - tqdm=4.47.0
  - pip
  - pip:
      - pandapower==2.4.0
      - nbstripout==0.3.9
      - mlflow==1.13.1
