name: eiv-grid-id
channels:
  - invenia
  - defaults
dependencies:
  - ipywidgets=7.5.1
  - jupyterlab=1.2.6
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandapower=2.1.0
  - pandas=1.0.3
  - plotly=4.7.1
  - python=3.7.7
  - scipy=1.4.1
  - pytest=5.4.2
