name: eiv-grid-id
channels:
  - invenia
  - defaults
  - conda-forge
dependencies:
  - ipywidgets=7.5.1
  - jupyterlab=2.1.4
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.0.3
  - plotly=4.7.1
  - python=3.7.7
  - scipy=1.4.1
  - pytest=5.4.2
  - pip
  - pip:
      - pandapower==2.2.2
      - nbstripout==0.3.7
