name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: 3.7

      - name: Check version
        run: |
          conda init bash
          conda --version
          which python

      - name: Install dependencies
        run: conda env update -f environment.yml

      - name: Select environment
        run: |
          conda activate eiv-grid-id

      - name: Test
        run: pytest test/



