name: CI

on: [ push ]

jobs:
  test:
    name: CI Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.5.0
        with:
          auto-update-conda: true
          python-version: 3.7
          activate-environment: eiv-grid-id
          environment-file: environment.yml
          auto-activate-base: false

      - name: Check version
        run: |
          conda --version
          which python

      - name: Test
        run: pytest test/



