name: CI

on: [ push ]

jobs:
  test:
    name: CI Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.5.0
        with:
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false

      - name: Test
        shell: bash -l {0}
        run: |
          conda activate eiv-grid-id
          conda --version
          which python
          pytest test/
