name: CI

on: [ push ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: 3.7
        run: |
          conda --version
          which python
